name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install toolchain
      run: |
        sudo apt update
        sudo apt --fix-missing install gcc-aarch64-linux-gnu iasl device-tree-compiler python3-pyelftools
    - name: Build
      run: |
        make sdcard -j$(nproc)
    
    - uses: actions/upload-artifact@v3
      with:
        name: Image
        path: /home/runner/work/quartz64_uefi/quartz64_uefi/ORANGEPI3B_EFI.img
